importdata LiBatteryData.mat

plot(time, current_C1,'xk', ...
    'LineWidth', 1,...
    'MarkerSize', 8,...
    'MarkerEdgeColor', '#77AC30' ...
    );
hold on
plot(time, current_2C1,'sb', ...
    'LineWidth', 1,...
    'MarkerSize', 8,...
    'MarkerEdgeColor', '#558761' ...
    );
plot(time, current_4C1,'og', ...
    'LineWidth', 1,...
    'MarkerSize', 8,...
    'MarkerEdgeColor', '#0072BD' ...
    );
xlabel('time in h', 'FontSize',15);
ylabel('current in v', 'FontSize', 15);
title('charateristic line: discharging Li-Ion Battery (temperature = 25°C)', FontSize=15)
legend('LiBattery C_1', 'LiBattery 2C_1', 'LiBattery 4C_1');
